/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lotto2app;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Conor, Camelia
 */
public class Lotto2GUI extends javax.swing.JFrame {

    String name;
    int userGuess[];
    int lottoNum[];
    int plus1[];
    int plus2[];
    int winNum;
    int winNum1;
    int winNum2;

    /**
     * Creates new form Lotto2GUI
     */
    public Lotto2GUI() {
        initComponents();

        lottoNum = new int[5];
        userGuess = new int[5];
        plus1 = new int[5];
        plus2 = new int[5];
        winNum = 0;
        winNum1 = 0;
        winNum2 = 0;
        name = " ";
        random();
        randomPlus1();
        randomPlus2();

    }

    private void random() {
        for (int i = 0; i < 5; i++) {
            lottoNum[i] = 1 + (int) (Math.random() * 50);
            for (int loop = 0; loop < lottoNum.length; loop++) {
                if (lottoNum[i] == Math.random()) {

                }
            }
        }
        System.out.println(Arrays.toString(lottoNum));
    }

    private void randomPlus1() {
        for (int i = 0; i < 5; i++) {
            plus1[i] = 1 + (int) (Math.random() * 50);
            for (int loop = 0; loop < plus1.length; loop++) {
                if (plus1[loop] == Math.random()) {

                }
            }
        }
        System.out.println(Arrays.toString(plus1));
    }

    private void randomPlus2() {
        for (int i = 0; i < 5; i++) {
            plus2[i] = 1 + (int) (Math.random() * 50);
            for (int loop = 0; loop < plus2.length; loop++) {
                if (plus2[loop] == Math.random()) {
                }
            }
        }
        System.out.println(Arrays.toString(plus2));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jFileChooser1 = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        titleLbl = new javax.swing.JLabel();
        userGuessLbl = new javax.swing.JLabel();
        userGuessTF1 = new javax.swing.JTextField();
        userGuessTF2 = new javax.swing.JTextField();
        userGuessTF3 = new javax.swing.JTextField();
        userGuessTF4 = new javax.swing.JTextField();
        userGuessTF5 = new javax.swing.JTextField();
        winNumRLbl = new javax.swing.JLabel();
        winNumLbl = new javax.swing.JLabel();
        winNum1Lbl = new javax.swing.JLabel();
        winNum1RLbl = new javax.swing.JLabel();
        winNum2Lbl = new javax.swing.JLabel();
        winNum2RLbl = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        nameJComboBox = new javax.swing.JComboBox<>();
        enterBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        writeBtn = new javax.swing.JButton();
        readBtn = new javax.swing.JButton();
        winNumaLbl = new javax.swing.JLabel();
        winNumbLbl = new javax.swing.JLabel();
        winNumcLbl = new javax.swing.JLabel();
        exitBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        jLabel1.setText("jLabel1");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotto2app/gb.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.orange);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.yellow);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLbl.setBackground(new java.awt.Color(255, 112, 112));
        titleLbl.setFont(new java.awt.Font("Sitka Small", 3, 36)); // NOI18N
        titleLbl.setText("Lottery Game");
        getContentPane().add(titleLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 270, 110));

        userGuessLbl.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        userGuessLbl.setText("Enter Numbers:");
        getContentPane().add(userGuessLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 200, 50));

        userGuessTF1.setBackground(new java.awt.Color(204, 204, 204));
        userGuessTF1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 0, 204), new java.awt.Color(153, 204, 255), null));
        userGuessTF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userGuessTF1ActionPerformed(evt);
            }
        });
        getContentPane().add(userGuessTF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 40, 30));

        userGuessTF2.setBackground(new java.awt.Color(204, 204, 204));
        userGuessTF2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 0, 204), new java.awt.Color(153, 204, 255), null));
        getContentPane().add(userGuessTF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 40, 30));

        userGuessTF3.setBackground(new java.awt.Color(204, 204, 204));
        userGuessTF3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 0, 204), new java.awt.Color(153, 204, 255), null));
        getContentPane().add(userGuessTF3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 40, 30));

        userGuessTF4.setBackground(new java.awt.Color(204, 204, 204));
        userGuessTF4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 0, 204), new java.awt.Color(153, 204, 255), null));
        getContentPane().add(userGuessTF4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 40, 30));

        userGuessTF5.setBackground(new java.awt.Color(204, 204, 204));
        userGuessTF5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 0, 204), new java.awt.Color(153, 204, 255), null));
        getContentPane().add(userGuessTF5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 40, 30));

        winNumRLbl.setBackground(new java.awt.Color(204, 204, 204));
        winNumRLbl.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        winNumRLbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 153, 51), new java.awt.Color(102, 255, 102), null));
        winNumRLbl.setOpaque(true);
        getContentPane().add(winNumRLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 40, 30));

        winNumLbl.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        winNumLbl.setText("You have guessed:");
        getContentPane().add(winNumLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 190, 40));

        winNum1Lbl.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        winNum1Lbl.setText("You have guessed: ");
        getContentPane().add(winNum1Lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 200, 40));

        winNum1RLbl.setBackground(new java.awt.Color(204, 204, 204));
        winNum1RLbl.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        winNum1RLbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 153, 51), new java.awt.Color(102, 255, 102), null));
        winNum1RLbl.setOpaque(true);
        getContentPane().add(winNum1RLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 40, 30));

        winNum2Lbl.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        winNum2Lbl.setText("You have guessed: ");
        getContentPane().add(winNum2Lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 190, 42));

        winNum2RLbl.setBackground(new java.awt.Color(204, 204, 204));
        winNum2RLbl.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        winNum2RLbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 153, 51), new java.awt.Color(102, 255, 102), null));
        winNum2RLbl.setOpaque(true);
        getContentPane().add(winNum2RLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 40, 30));

        nameLbl.setBackground(new java.awt.Color(204, 204, 204));
        nameLbl.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        nameLbl.setText("Choose Draw:");
        getContentPane().add(nameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 150, 40));

        nameJComboBox.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.select"));
        nameJComboBox.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        nameJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lotto", "Plus 1", "Plus 2" }));
        nameJComboBox.setAutoscrolls(true);
        nameJComboBox.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, javax.swing.UIManager.getDefaults().getColor("Button.disabledToolBarBorderBackground"), new java.awt.Color(204, 204, 204), null));
        nameJComboBox.setOpaque(false);
        nameJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameJComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(nameJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 120, 29));
        nameJComboBox.getAccessibleContext().setAccessibleName("");

        enterBtn.setFont(new java.awt.Font("Sitka Small", 3, 18)); // NOI18N
        enterBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotto2app/Star1.png"))); // NOI18N
        enterBtn.setText("Submit");
        enterBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 153), new java.awt.Color(102, 255, 255), null));
        enterBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        enterBtn.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        enterBtn.setOpaque(false);
        enterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterBtnActionPerformed(evt);
            }
        });
        getContentPane().add(enterBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, 160, 70));

        resetBtn.setFont(new java.awt.Font("Sitka Small", 3, 18)); // NOI18N
        resetBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotto2app/balwLottoBalls.png"))); // NOI18N
        resetBtn.setText("New Game");
        resetBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 102, 102), new java.awt.Color(51, 255, 102), null));
        resetBtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        resetBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });
        getContentPane().add(resetBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 590, 310, 70));

        writeBtn.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        writeBtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        writeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotto2app/bbl.png"))); // NOI18N
        writeBtn.setText("Save");
        writeBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 0), new java.awt.Color(102, 102, 102)));
        writeBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        writeBtn.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        writeBtn.setOpaque(false);
        writeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                writeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(writeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 180, 60));

        readBtn.setBackground(javax.swing.UIManager.getDefaults().getColor("CheckBoxMenuItem.acceleratorForeground"));
        readBtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        readBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotto2app/lottery-balls.png"))); // NOI18N
        readBtn.setText("Load");
        readBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 153, 255)));
        readBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readBtnActionPerformed(evt);
            }
        });
        getContentPane().add(readBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 180, 60));

        winNumaLbl.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.focus"));
        winNumaLbl.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        winNumaLbl.setText("numbers on \"Lotto\" draw!");
        winNumaLbl.setOpaque(true);
        getContentPane().add(winNumaLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 280, 30));

        winNumbLbl.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.focus"));
        winNumbLbl.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        winNumbLbl.setText("numbers on \"Plus 1\" draw!");
        winNumbLbl.setOpaque(true);
        getContentPane().add(winNumbLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 280, -1));

        winNumcLbl.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.focus"));
        winNumcLbl.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        winNumcLbl.setText("numbers on \"Plus 2\" draw! ");
        winNumcLbl.setOpaque(true);
        getContentPane().add(winNumcLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 280, -1));

        exitBtn.setFont(new java.awt.Font("Sitka Small", 3, 18)); // NOI18N
        exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotto2app/balwLottoBalls.png"))); // NOI18N
        exitBtn.setText("Exit Game");
        exitBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(204, 204, 204)));
        exitBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        exitBtn.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        exitBtn.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        exitBtn.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        getContentPane().add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 320, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotto2app/lottery-146318_1280.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 690));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, -1));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 790, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userGuessTF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userGuessTF1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_userGuessTF1ActionPerformed


    private void enterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterBtnActionPerformed
        // TODO add your handling code here

        userGuess[0] = Integer.parseInt(userGuessTF1.getText());
        userGuess[1] = Integer.parseInt(userGuessTF2.getText());
        userGuess[2] = Integer.parseInt(userGuessTF3.getText());
        userGuess[3] = Integer.parseInt(userGuessTF4.getText());
        userGuess[4] = Integer.parseInt(userGuessTF5.getText());

        String name = (String) nameJComboBox.getSelectedItem();

        if (name.equals("Lotto")) {
            for (int i = 0; i < 5; i++) {
                if (userGuess[i] == lottoNum[0] || userGuess[i] == lottoNum[1] || userGuess[i] == lottoNum[2] || userGuess[i] == lottoNum[3] || userGuess[i] == lottoNum[4]) {
                    winNum++;
                }
            }
            winNumRLbl.setText(Integer.toString(winNum));

        }

        if (name.equals("Plus 1")) {
            for (int i = 0; i < 5; i++) {
                if (userGuess[i] == lottoNum[0] || userGuess[i] == lottoNum[1] || userGuess[i] == lottoNum[2] || userGuess[i] == lottoNum[3] || userGuess[i] == lottoNum[4]) {
                    winNum++;
                }
            }
            for (int i = 0; i < 5; i++) {
                if (userGuess[i] == plus1[0] || userGuess[i] == plus1[1] || userGuess[i] == plus1[2] || userGuess[i] == plus1[3] || userGuess[i] == plus1[4]) {
                    winNum1++;

                }
            }
            winNumRLbl.setText(Integer.toString(winNum));
            winNum1RLbl.setText(Integer.toString(winNum1));

        }

        if (name.equals("Plus 2")) {
            for (int i = 0; i < 5; i++) {
                if (userGuess[i] == lottoNum[0] || userGuess[i] == lottoNum[1] || userGuess[i] == lottoNum[2] || userGuess[i] == lottoNum[3] || userGuess[i] == lottoNum[4]) {
                    winNum++;
                }
            }
            for (int i = 0; i < 5; i++) {
                if (userGuess[i] == plus1[0] || userGuess[i] == plus1[1] || userGuess[i] == plus1[2] || userGuess[i] == plus1[3] || userGuess[i] == plus1[4]) {
                    winNum1++;

                }
            }
            for (int i = 0; i < 5; i++) {
                if (userGuess[i] == plus2[0] || userGuess[i] == plus2[1] || userGuess[i] == plus2[2] || userGuess[i] == plus2[3] || userGuess[i] == plus2[4]) {
                    winNum2++;

                }
            }
            winNum2RLbl.setText(Integer.toString(winNum2));
            winNumRLbl.setText(Integer.toString(winNum));
            winNum1RLbl.setText(Integer.toString(winNum1));

        }

    }//GEN-LAST:event_enterBtnActionPerformed

    private void nameJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameJComboBoxActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_nameJComboBoxActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO add your handling code here:

        dispose();
        Lotto2GUI l = new Lotto2GUI();
        l.show();
    }//GEN-LAST:event_resetBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void writeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_writeBtnActionPerformed
        // TODO add your handling code here:
        userGuess[0] = Integer.parseInt(userGuessTF1.getText());
        userGuess[1] = Integer.parseInt(userGuessTF2.getText());
        userGuess[2] = Integer.parseInt(userGuessTF3.getText());
        userGuess[3] = Integer.parseInt(userGuessTF4.getText());
        userGuess[4] = Integer.parseInt(userGuessTF5.getText());

        Lotto2 l = new Lotto2();
        l.setUserGuess(userGuess);

        File outFile;
        FileOutputStream fStream;
        ObjectOutputStream oStream;

        try {
            outFile = new File("StoredNumbers.data");
            fStream = new FileOutputStream(outFile);
            oStream = new ObjectOutputStream(fStream);

            oStream.writeObject(l);
            JOptionPane.showMessageDialog(null, "Strored numbers sucessfully writen to File");

            oStream.close();

        } catch (IOException e) {
            System.out.println(e.toString() + "Error writting to File:");
        }
    }//GEN-LAST:event_writeBtnActionPerformed

    private void readBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readBtnActionPerformed
        // TODO add your handling code here:
        /*userGuess[0] = Integer.parseInt(userGuessTF1.getText());
        userGuess[1] = Integer.parseInt(userGuessTF2.getText());
        userGuess[2] = Integer.parseInt(userGuessTF3.getText());
        userGuess[3] = Integer.parseInt(userGuessTF4.getText());
        userGuess[4] = Integer.parseInt(userGuessTF5.getText());*/

        File inFile;
        FileInputStream fStream;
        ObjectInputStream oStream;

        try {
            inFile = new File("StoredNumbers.data");
            fStream = new FileInputStream(inFile);
            oStream = new ObjectInputStream(fStream);

            Lotto2 l;
            l = (Lotto2) oStream.readObject();
            if (l != null) {
                int[] ug = l.getUserGuess();
                userGuessTF1.setText(ug[0] + "");

            }
            if (l != null) {
                int[] ug = l.getUserGuess();
                userGuessTF2.setText(ug[1] + "");

            }
            if (l != null) {
                int[] ug = l.getUserGuess();
                userGuessTF3.setText(ug[2] + "");

            }
            if (l != null) {
                int[] ug = l.getUserGuess();
                userGuessTF4.setText(ug[3] + "");

            }
            if (l != null) {
                int[] ug = l.getUserGuess();
                userGuessTF5.setText(ug[4] + "");

            }
            
            
            oStream.close();
        } catch (IOException | ClassNotFoundException e) {
            System.out.println(e.toString() + "Error reading from File");
        }
    }//GEN-LAST:event_readBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lotto2GUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lotto2GUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lotto2GUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lotto2GUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lotto2GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enterBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> nameJComboBox;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JButton readBtn;
    private javax.swing.JButton resetBtn;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JLabel userGuessLbl;
    private javax.swing.JTextField userGuessTF1;
    private javax.swing.JTextField userGuessTF2;
    private javax.swing.JTextField userGuessTF3;
    private javax.swing.JTextField userGuessTF4;
    private javax.swing.JTextField userGuessTF5;
    private javax.swing.JLabel winNum1Lbl;
    private javax.swing.JLabel winNum1RLbl;
    private javax.swing.JLabel winNum2Lbl;
    private javax.swing.JLabel winNum2RLbl;
    private javax.swing.JLabel winNumLbl;
    private javax.swing.JLabel winNumRLbl;
    private javax.swing.JLabel winNumaLbl;
    private javax.swing.JLabel winNumbLbl;
    private javax.swing.JLabel winNumcLbl;
    private javax.swing.JButton writeBtn;
    // End of variables declaration//GEN-END:variables
}
